// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwojnfhvlaipfqgvfqlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3b2puZmh2bGFpcGZxZ3ZmcWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDE5MjIsImV4cCI6MjA2NTQxNzkyMn0.YFxyp_B-iRdInP7vQZj36q4q5djQ2Bi9HkSE_2NvU4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);